[project]
name = "stellargraph"
version = "0.1.0"
description = ""
authors = [
    {name = "fcas",email = "f3l1nux@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "setuptools (>=84.0.0,<85.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
